name: Build G4F Docker Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup G4F
        run: |
          set -e
          git clone https://github.com/xtekky/gpt4free
          cd gpt4free
          echo '
          @@ -1,4 +1,4 @@
          -FROM selenium/node-chrome
          +FROM selenium/node-chromium
           
           ARG G4F_VERSION
           ENV G4F_VERSION $G4F_VERSION
          ' | patch -p1 doc/Dockerfile
          echo "ref_name=$(git symbolic-ref --short HEAD 2>/dev/null || git describe --tags --exact-match 2>/dev/null || echo "detached")" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME  }}
          password: ${{ secrets.DOCKERHUB_TOKEN  }}

      - name: Build and push arm64 image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/g4f:latest
          labels: ${{ secrets.DOCKERHUB_USERNAME }}/g4f:latest
          build-args: |
            G4F_VERSION=${{ env.ref_name }}
